[project]
name = "mydeck"
version = "0.1.0"

dependencies = [
  "streamdeck",
  "Pillow",
  "aiohttp"
]

[project.scripts]
mydeck = "mydeck.main:main"

[project.optional-dependencies]
dev = [
  "black",
  "mypy"
]
